### ISSUE TITLE
incorrect link for offline download thingy

### ISSUE THREAD

**Issue by 22yeetz22** [LateAlways/Fuchsia-X-EAGLERCRAFT#1]
in stable-download/offline-download-version.html

should be fuchsia x but it is the outdated lax1dude repo

this line; <h2>you are running eaglercraft locally, check <a href="https://github.com/LAX1DUDE/eaglercraft/blob/main/stable-download/Offline_Download_Version.html" target="_blank">this link</a> regularly for an updated version</h2>

**Comment by LateAlways** [comment]
Fixed
