### ISSUE TITLE
"Step" Hack does not have desription text.

### ISSUE THREAD

**Issue by 22yeetz22** [LateAlways/Fuchsia-X-EAGLERCRAFT#7]
when hovering over the step hack, does not show alt text.

searching for this text in the source code will put you to the left of where you need to fix: "Lets you climb on walls like if it was a ladder."

**Comment by LateAlways** [comment]
Removed Step

**Comment by 22yeetz22** [comment]
@LateAlways what was the step hack supposed to do anyways?
