### ISSUE TITLE
Using Alt Generator Returns Error

### ISSUE THREAD

**Issue by 22yeetz22** [LateAlways/Fuchsia-X-EAGLERCRAFT#9]
Error:

Game Crashed! I have fallen and I can't get up! If this has happened more than once then please copy the text on this screen and publish it in the issues feed of this fork's GitHub repository.

The URL to this fork's GitHub repository is: https://github.com/lax1dude/eaglercraft

java.lang.IndexOutOfBoundsException

Error: Java exception thrown
    at $rt_exception (file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html:154:390)
    at $rt_throw (file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html:154:218)
    at AMz (file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html:3903:62)
    at Bd (file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html:3895:18)
    at BMx (file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html:16107:239)
    at $rt_array.toString [as d8] (file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html:20583:385)
    at BfN (file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html:5020:403)
    at $rt_array.toString [as hl] (file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html:20262:474)
    at Bf9 (file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html:5029:158)
    at $rt_array.toString [as PL] (file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html:20263:178)

eaglercraft.version = "22w43a"
eaglercraft.minecraft = "1.5.2"
eaglercraft.brand = "lax1dude"
eaglercraft.username = "Nightshade"

webgl.version = WebGL 2.0 (OpenGL ES 3.0 Chromium)
webgl.renderer = ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
webgl.vendor = Google Inc. (AMD)

webgl.anisotropicGlitch = true

window.eaglercraftOpts = {"container":"game_frame","relays":[{"addr":"wss://relay.deev.is/","primary":false,"name":"lax1dude relay #1"},{"addr":"wss://relay.lax1dude.net/","primary":false,"name":"lax1dude relay #2"},{"addr":"wss://relay.shhnowisnottheti.me/","primary":true,"name":"ayunami relay #1"}],"mainMenu":{"splashes":["Darviglet!","eaglerenophile!","You Eagler!","Yeeeeeee!","yeee","EEEEEEEEE!","You Darvig!","You Vigg!",":>","|>","You Yumpster!"]},"assetsURI":"data:application/octet-stream;base64,RUFHUEtHJCQGdmVyMi4wCmFzc2V0cy5lcGsAWAoKICMgIEVhZ2xlciBFUEsgdjIuMCAoYykgMjAyMyBDYWxkZXIgWW91bmcKICMgIHVwZGF0ZTogb24gMDIvMTgvMjAyMyBhdCAwNToyMzo0OCBwLm0uCgoAAAGGZqBVBQAABVFHH4sIAAAAAAAC/+y8dXgWV7c2/hAsePDgBAJFBhif2UCDS4D ... ","serverWorkerURI":"blob:null/21ad7013-99a4-44b5-b00f-9816e20d15c4","worldsFolder":"OFFLINE"}

window.navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 12
window.navigator.deviceMemory = 8
window.navigator.platform = Win32
window.navigator.product = Gecko

rootElement.clientWidth = 1920
rootElement.clientHeight = 961
window.innerWidth = 1920
window.innerHeight = 961
window.outerWidth = 1920
window.outerHeight = 1032
window.devicePixelRatio = 1
window.screen.availWidth = 1920
window.screen.availHeight = 1032
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.location.href = file:///C:/Users/chang/OneDrive/%E6%A1%8C%E9%9D%A2/McHackedClient.html

----- Begin Minecraft Config -----
CgAAAQAXTm90aWZpY2F0aW9uc19pc0VuYWJsZWQAAwANUmVhY2hfa2V5Q29kZQAAAAADAAhrZXkuem9vbQAAAC4BACFBdXRvRGlzYWJsZV9Cb29sU2V0dGluZ19EaXNwbGF5ZWQBAQALV29ybGRfc2hvd24BAQAOV1RhcF9pc0VuYWJsZWQAAwAGTWlzY194AAAATgEAD2NoYXRMaW5rc1Byb21wdAEDAAZNaXNjX3kAAAAJBQAdQXV0b0Jsb2NrX051bWJlclNldHRpbmdfRGVsYXlBcAAABQAtw4LCpzbDosWhwqDDgsKnciBLaWxsQXVyYV9OdW1iZXJTZXR0aW5nX1JhbmdlQIAAAAMAJcOCwqc2w6LFocKgw4LCp3IgTm9DbGlja0RlbGF5X2tleUNvZGUAAAAAAwAIQ29tYmF0X3gAAADyAwAIQ29tYmF0X3kAAABIAQAVQXV0b0Rpc2FibGVfaXNFbmFibGVkAAEALcOCwqc2w6LFocKgw4LCp3IgS2lsbEF1cmFfQm9vbFNldHRpbmdfQW50aUJvdAAFABF2b2ljZUxpc3RlblZvbHVtZT8AAAAFAC7DgsKnNsOixaHCoMOCwqdyIEZhc3RQbGFjZV9OdW1iZXJTZXR0aW5nX0RlbGF5AAAAAAEAH0FpbUFzc2lzdF9Cb29sU2V0dGluZ19EaXNwbGF5ZWQBAQANRVNQX2lzRW5hYmxlZAABAApNaXNjX3Nob3duAQEAJcOCwqc2w6LFocKgw4LCp3IgTm9TbG93ZG93bl9pc0VuYWJsZWQAAQAgVmVsb2NpdHlfQm9vbFNldHRpbmdfTm8gdmVsb2NpdHkAAQALc2hvd1NraW5IYXQBCAAURmx5X01vZGVTZXR0aW5nX01vZGUAB1ZhbmlsbGEFAB5FU1BfTnVtYmVyU2V0dGluZ19CbHVlIFZhbHVlOiAAAAAAAQAMQ29tYmF0X3Nob3duAQEAH0F1dG9CbG9ja19Cb29sU2V0dGluZ19EaXNwbGF5ZWQBAQAfw4LCpzbDosWhwqDDgsKnciBTdGVwX2lzRW5hYmxlZAADAAhSZW5kZXJfeAAAAOUDAAhSZW5kZXJfeQAAAIIDABFNb3ZlbWVudF9tYXhXaWR0aAAAAIwDACfDgsKnNsOixaHCoMOCwqdyIEtpbGxBdXJhX1JFTkRFUl9IRUlHSFQAAAAyAwAIa2V5LmxlZnQAAAAeAwALa2V5LmZvcndhcmQAAAARAwAPUGxheWVyX21heFdpZHRoAAAAjAEAIcOCwqc2w6LFocKgw4LCp3IgU3BpZGVyX2lzRW5hYmxlZAABACTDgsKnNsOixaHCoMOCwqdyIEZhc3RQbGFjZV9pc0VuYWJsZWQAAQAeTm9Sb3RhdGVfQm9vbFNldHRpbmdfRGlzcGxheWVkAQMAEE5vUm90YXRlX2tleUNvZGUAAAAAAQAjw4LCpzbDosWhwqDDgsKnciBTYWZlV2Fsa19pc0VuYWJsZWQAAwAObGltaXRGcmFtZXJhdGUAAAAAAQAMUGxheWVyX3Nob3duAAEAFHNlZW5BY2tub3dsZWRnZW1lbnRzAQEAFEtleXN0cm9rZXNfaXNFbmFibGVkAAMAI8OCwqc2w6LFocKgw4LCp3IgTm9TbG93ZG93bl9rZXlDb2RlAAAAAAMAHcOCwqc2w6LFocKgw4LCp3IgU3RlcF9rZXlDb2RlAAAAAAMACGtleS5qdW1wAAAAOQMAIsOCwqc2w6LFocKgw4LCp3IgQ3JpdGljYWxzX2tleUNvZGUAAAAAAwAMWFJheV9rZXlDb2RlAAAAAAEAKMOCwqc2w6LFocKgw4LCp3IgS2lsbEF1cmFfSXNSZW5kZXJNb2R1bGUBAQALdG91Y2hzY3JlZW4AAQALaW52ZXJ0TW91c2UAAQAgRnVsbEJyaWdodF9Cb29sU2V0dGluZ19EaXNwbGF5ZWQBAQANZmFuY3lHcmFwaGljcwADABVOb3RpZmljYXRpb25zX2tleUNvZGUAAAAAAwAiw4LCpzbDosWhwqDDgsKnciBBdXRvQXJtb3Jfa2V5Q29kZQAAAAABAC7DgsKnNsOixaHCoMOCwqdyIENoZXN0U3RlYWxlcl9Cb29sU2V0dGluZ19BdXJhAAEAFEZ1bGxCcmlnaHRfaXNFbmFibGVkAQMADGtleS5mdW5jdGlvbgAAACEDAAprZXkuc3ByaW50AAAAEwMADmNoYXRWaXNpYmlsaXR5AAAAAAMAIsOCwqc2w6LFocKgw4LCp3IgS2lsbEF1cmFfUkVOREVSX1gAAAAKAwAiw4LCpzbDosWhwqDDgsKnciBLaWxsQXVyYV9SRU5ERVJfWQAAAAoBABlFU1BfQm9vbFNldHRpbmdfRGlzcGxheWVkAQEAEHNob3dTa2luUmlnaHRMZWcBAwANa2V5LmludmVudG9yeQAAABIBABZBdXRvLUNsaWNrZXJfaXNFbmFibGVkAAEAGUtleXN0cm9rZXNfSXNSZW5kZXJNb2R1bGUBBQAzw4LCpzbDosWhwqDDgsKnciBLaWxsQXVyYV9OdW1iZXJTZXR0aW5nX01heGltdW0gQ1BTQXAAAAUAJkF1dG8tQ2xpY2tlcl9OdW1iZXJTZXR0aW5nX01pbmltdW0gQ1BTQVAAAAUAL8OCwqc2w6LFocKgw4LCp3IgU3BlZWRfTnVtYmVyU2V0dGluZ19NdWx0aXBsaWVyQcgAAAMADU1pc2NfbWF4V2lkdGgAAACMAQATTm9IdXJ0Q2FtX2lzRW5hYmxlZAABABBQbGF5ZXJfY29sbGFwc2VkAQUAC3NlbnNpdGl2aXR5PxA5sQUAF0ZseV9OdW1iZXJTZXR0aW5nX1NwZWVkPczMzQUANcOCwqc2w6LFocKgw4LCp3IgSW52ZW50b3J5Q2xlYW5lcl9OdW1iZXJTZXR0aW5nX0RlbGF5QzQAAAMACXBhcnRpY2xlcwAAAAEDABNLZXlzdHJva2VzX1JFTkRFUl9YAAAACgMAE0tleXN0cm9rZXNfUkVOREVSX1kAAAAKAQAWQ2F0ZWdvcnlMaXN0X2NvbGxhcHNlZAADAB/DgsKnNsOixaHCoMOCwqdyIFNwaWRlcl9rZXlDb2RlAAAAAAMAIsOCwqc2w6LFocKgw4LCp3IgRmFzdFBsYWNlX2tleUNvZGUAAAAAAwAKa2V5LmF0dGFja////5wDAAxSZW5kZXJfbGFzdFj////OAwAMUmVuZGVyX2xhc3RZ////9wMACFBsYXllcl94AAAAAAMACFBsYXllcl95AAAAAAEAGUZseV9Cb29sU2V0dGluZ19EaXNwbGF5ZWQBAQADZm9nAQEAD3Nob3dDb29yZGluYXRlcwEDABRBdXRvLUNsaWNrZXJfa2V5Q29kZQAAAAADAAlrZXkuc25lYWsAAAAqAwAVQ2F0ZWdvcnlMaXN0X21heFdpZHRoAAAAbgEAJMOCwqc2w6LFocKgw4LCp3IgQXV0b0FybW9yX2lzRW5hYmxlZAADABNBdXRvRGlzYWJsZV9rZXlDb2RlAAAAAAEALcOCwqc2w6LFocKgw4LCp3IgS2lsbEF1cmFfQm9vbFNldHRpbmdfTm9Td2luZwADACnDgsKnNsOixaHCoMOCwqdyIEludmVudG9yeUNsZWFuZXJfa2V5Q29kZQAAAAABAA9SZWFjaF9pc0VuYWJsZWQAAwARTm9IdXJ0Q2FtX2tleUNvZGUAAAAAAQAiU3ByaW50X0Jvb2xTZXR0aW5nX011bHRpLURpcmVjdGlvbgAFAANmb3Y/YyepBQAZUmVhY2hfTnVtYmVyU2V0dGluZ19SZWFjaECAAAADAAhndWlTY2FsZQAAAAMBACzDgsKnNsOixaHCoMOCwqdyIEtpbGxBdXJhX0Jvb2xTZXR0aW5nX1JvdGF0ZQEFAAljaGF0U2NhbGU/gAAAAQASTm9Sb3RhdGVfaXNFbmFibGVkAAUAGFdUYXBfTnVtYmVyU2V0dGluZ19EZWxheUCgAAABABBoZWxkSXRlbVRvb2x0aXBzAQMAJsOCwqc2w6LFocKgw4LCp3IgS2lsbEF1cmFfUkVOREVSX1dJRFRIAAAAyAEAEHNob3dTa2luUmlnaHRBcm0BAQAGY2xvdWRzAAUAE2NoYXRIZWlnaHRVbmZvY3VzZWQ+4yepAQAOTWlzY19jb2xsYXBzZWQAAQASTW92ZW1lbnRfY29sbGFwc2VkAAMAB1dvcmxkX3gAAAA9AwAHV29ybGRfeQAAAOcBABBDb21iYXRfY29sbGFwc2VkAQMADldvcmxkX21heFdpZHRoAAAAjAEAE0FycmF5TGlzdF9pc0VuYWJsZWQAAQAlTm90aWZpY2F0aW9uc19Cb29sU2V0dGluZ19Nb2QgVG9nZ2xlcwEDAA1hbnRpYWxpYXNNb2RlAAAAAQMAIcOCwqc2w6LFocKgw4LCp3IgS2lsbEF1cmFfa2V5Q29kZQAAAAABABBTcHJpbnRfaXNFbmFibGVkAAUAEHZvaWNlU3BlYWtWb2x1bWU/AAAAAwALRmx5X2tleUNvZGUAAAAAAwAXS2V5c3Ryb2tlc19SRU5ERVJfV0lEVEgAAABkBQAfRVNQX051bWJlclNldHRpbmdfR3JlZW4gVmFsdWU6IAAAAAADACHDgsKnNsOixaHCoMOCwqdyIFNhZmVXYWxrX2tleUNvZGUAAAAAAwAKTW92ZW1lbnRfeAAAAasFAAtzb3VuZFZvbHVtZT6bCtEDAApNb3ZlbWVudF95AAAAWQEAD3Nob3dTa2luTGVmdExlZwEDABhLZXlzdHJva2VzX1JFTkRFUl9IRUlHSFQAAAEsAQAQUmVuZGVyX2NvbGxhcHNlZAEBABFoaWRlU2VydmVyQWRkcmVzcwABAA5hbGxvd0ZOQVdTa2lucwEDAAtFU1Bfa2V5Q29kZQAAAAABAAt2aWV3Qm9iYmluZwEBABBhZHZhbmNlZFRvb2x0aXBzAAMADk1vdmVtZW50X2xhc3RY////kQMADk1vdmVtZW50X2xhc3RZ////+QEAK8OCwqc2w6LFocKgw4LCp3IgSW52ZW50b3J5Q2xlYW5lcl9pc0VuYWJsZWQAAwAIa2V5LmJhY2sAAAAfAwAIa2V5LmRyb3AAAAAQAQAQcGF1c2VPbkxvc3RGb2N1cwEFACNBaW1Bc3Npc3RfTnVtYmVyU2V0dGluZ19IaXRib3ggU2l6ZUBAAAADAAt2b2ljZVBUVEtleQAAAC8DABFBcnJheUxpc3Rfa2V5Q29kZQAAAAADAA9SZW5kZXJfbWF4V2lkdGgAAACMBQApVmVsb2NpdHlfTnVtYmVyU2V0dGluZ19WZXJ0aWNhbCBLbm9ja2JhY2s/gAAAAwASRnVsbEJyaWdodF9rZXlDb2RlAAAAAAUAJkF1dG9CbG9ja19OdW1iZXJTZXR0aW5nX0Jsb2NrIER1cmF0aW9uQaAAAAEACWNoYXRMaW5rcwEBAAxSZW5kZXJfc2hvd24BBQAJY2hhdFdpZHRoP4AAAAUAHUVTUF9OdW1iZXJTZXR0aW5nX1JlZCBWYWx1ZTogQ38AAAgACGxhbmd1YWdlAAVlbl9VUwEAD3Nob3dTa2luTGVmdEFybQEDABJDYXRlZ29yeUxpc3RfbGFzdFj////pAwASQ2F0ZWdvcnlMaXN0X2xhc3RZ////+gEAHFNwcmludF9Cb29sU2V0dGluZ19EaXNwbGF5ZWQBAQAOWFJheV9pc0VuYWJsZWQAAQAIc2hvd0NhcGUBAQAjTm90aWZpY2F0aW9uc19Cb29sU2V0dGluZ19EaXNwbGF5ZWQBAwAew4LCpzbDosWhwqDDgsKnciBTcGVlZF9rZXlDb2RlAAAAAAMAC1dvcmxkX2xhc3RY////6AEAGldUYXBfQm9vbFNldHRpbmdfRGlzcGxheWVkAQMAC1dvcmxkX2xhc3RZ////+AEAIcOCwqc2w6LFocKgw4LCp3IgTm9GYWxsX2lzRW5hYmxlZAADAAdrZXkudXNl////nQMADFdUYXBfa2V5Q29kZQAAAAAIAApsYXN0U2VydmVyAAABACPDgsKnNsOixaHCoMOCwqdyIEtpbGxBdXJhX2lzRW5hYmxlZAABACJBdXRvLUNsaWNrZXJfQm9vbFNldHRpbmdfRGlzcGxheWVkAQUAM8OCwqc2w6LFocKgw4LCp3IgS2lsbEF1cmFfTnVtYmVyU2V0dGluZ19NaW5pbXVtIENQU0FwAAADAAxrZXkucGlja0l0ZW3///+eAwAIa2V5LmNoYXQAAAAUAQAOc2hvd1NraW5KYWNrZXQBAQAfTm9IdXJ0Q2FtX0Jvb2xTZXR0aW5nX0Rpc3BsYXllZAEDABF2b2ljZUxpc3RlblJhZGl1cwAAABADACXDgsKnNsOixaHCoMOCwqdyIENoZXN0U3RlYWxlcl9rZXlDb2RlAAAAAAMAD0NvbWJhdF9tYXhXaWR0aAAAAIwDAApNaXNjX2xhc3RY////0gUAGkZseV9OdW1iZXJTZXR0aW5nX0Nvb2xkb3duAAAAAAkAB3NlcnZlcnMKAAAAAgEAC2hpZGVBZGRyZXNzAAgAAmlwABt3c3M6Ly93ZWIuYXNzcGl4ZWwubmV0L0NBUC8IAARuYW1lAAhBc3NwaXhlbAABAAtoaWRlQWRkcmVzcwAIAAJpcAAWd3NzOi8vd2F0ZXItbmV0d29yay50awgABG5hbWUADVdhdGVyIE5ldHdvcmsAAwAKTWlzY19sYXN0Wf////YBAAxyZWxheVRpbWVvdXQEBQALY2hhdE9wYWNpdHk/gAAAAQAnw4LCpzbDosWhwqDDgsKnciBDaGVzdFN0ZWFsZXJfaXNFbmFibGVkAAMADENvbWJhdF9sYXN0WP///+wDAAxDb21iYXRfbGFzdFn////4AQAMaGlkZUpvaW5Db2RlAAMAEUFpbUFzc2lzdF9rZXlDb2RlAAAAAAMACmZvcmNlV2lkdGgAAAAAAwAMY2h1bmtVcGRhdGVzAAAAAAUAC211c2ljVm9sdW1lPhdvxgEADk1vdmVtZW50X3Nob3duAQEAE0FpbUFzc2lzdF9pc0VuYWJsZWQABQAmQXV0by1DbGlja2VyX051bWJlclNldHRpbmdfTWF4aW11bSBDUFNBcAAABQAFZ2FtbWFBIAAAAQAkw4LCpzbDosWhwqDDgsKnciBDcml0aWNhbHNfaXNFbmFibGVkAAMAEFZlbG9jaXR5X2tleUNvZGUAAAAAAwARQXV0b0Jsb2NrX2tleUNvZGUAAAAAAQAWRmx5X0Jvb2xTZXR0aW5nX05vS2ljawEDAB/DgsKnNsOixaHCoMOCwqdyIE5vRmFsbF9rZXlDb2RlAAAAAAEADnNob3dPdGhlckNhcGVzAQEAC2NoYXRDb2xvdXJzAQEAE0F1dG9CbG9ja19pc0VuYWJsZWQAAwAMdmlld0Rpc3RhbmNlAAAAAwEACmRpZmZpY3VsdHkBAQAbUmVhY2hfQm9vbFNldHRpbmdfRGlzcGxheWVkAQMADFBsYXllcl9sYXN0WAAAAAABACBLZXlzdHJva2VzX0Jvb2xTZXR0aW5nX0Rpc3BsYXllZAEDAAxQbGF5ZXJfbGFzdFkAAAAABQAZRmx5X051bWJlclNldHRpbmdfVXBTcGVlZD11wo8DABJLZXlzdHJva2VzX2tleUNvZGUAAAAAAQAPV29ybGRfY29sbGFwc2VkAQEADUZseV9pc0VuYWJsZWQAAwAJa2V5LnJpZ2h0AAAAIAEACGFkZGVyYWxsAAgAMMOCwqc2w6LFocKgw4LCp3IgQ3JpdGljYWxzX01vZGVTZXR0aW5nX0NyaXRpY2FscwAGUGFja2V0AwAOQ2F0ZWdvcnlMaXN0X3gAAAAPAwAQYW1iaWVudE9jY2x1c2lvbgAAAAADAA5DYXRlZ29yeUxpc3RfeQAAACQBACfDgsKnNsOixaHCoMOCwqdyIE5vQ2xpY2tEZWxheV9pc0VuYWJsZWQAAQAIYW5hZ2x5cGgABQARY2hhdEhlaWdodEZvY3VzZWQ/gAAABQArVmVsb2NpdHlfTnVtYmVyU2V0dGluZ19Ib3Jpem9udGFsIEtub2NrYmFjaz+AAAABAApmdWxsU2NyZWVuAAEAGlhSYXlfQm9vbFNldHRpbmdfRGlzcGxheWVkAQEAHlZlbG9jaXR5X0Jvb2xTZXR0aW5nX0Rpc3BsYXllZAEDAA5TcHJpbnRfa2V5Q29kZQAAAAAFABtGbHlfTnVtYmVyU2V0dGluZ19GYWxsU3BlZWQ7xJumBQAxw4LCpzbDosWhwqDDgsKnciBDaGVzdFN0ZWFsZXJfTnVtYmVyU2V0dGluZ19EZWxheUMWAAADAA5rZXkucGxheWVybGlzdAAAAA8BABJDYXRlZ29yeUxpc3Rfc2hvd24BAwALZm9yY2VIZWlnaHQAAAAAAQASVmVsb2NpdHlfaXNFbmFibGVkAAEAIMOCwqc2w6LFocKgw4LCp3IgU3BlZWRfaXNFbmFibGVkAAA=
----- End Minecraft Config -----

window.minecraftServer = null

**Comment by LateAlways** [comment]
Fixed
